# Generated by Django 6.0.3 on 2026-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontrolador',
            name='mac_address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
